### ISSUE TITLE
surface-layers.xml discussion

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlr-protocols#1]
Things I'm unsure about:

* ~~Manual positioning - this is there to support more use-cases but involves some iffy stuff (using output device physical coordinates)~~
* The list of defined layers
* ~~Exclusivity - this is there to support, for example, panels that take up space on the bottom of the screen and shouldn't normally be occluded. But implementation-wise it's hairy. It may be better to make this a seperate protocol.~~

**Comment by SirCmpwn** [comment]
Submitted to wayland-devel for further discussion.

**Comment by Drakulix** [comment]
I have tried to read up the discussion on wayland-devel, is this the latest message on the subject?

https://lists.freedesktop.org/archives/wayland-devel/2017-January/032832.html

If yes, whats the state now, everybody continues to do what he wants and the wayland developers are not suggesting a common protocol to handle shell ui?
Which means except for some smaller compositors nobody will really care?

**Comment by SirCmpwn** [comment]
Yep.

**Comment by Drakulix** [comment]
How frustratingly disappointing

**Comment by samuelsadok** [comment]
Since currently a merger into wayland-protocols seems unlikely, I think merging into wayland-wall would still be widely beneficial. This protocol covers the use cases of several of the wayland-wall protocols so ideally the older redundant protocols could be deprecated and the clients that already implement it could be adapted.
But as long as it's just lying around here it won't be used outside of sway and that's sad because it clearly has great potential.

**Comment by SirCmpwn** [comment]
We're still iterating on this in wlroots before we submit the final proposal to wayland-devel. An implementation is being developed which will land in at least Sway, Way Cooler, and Waymonad. I still do not plan to implement wayland-wall.

**Comment by samuelsadok** [comment]
Ok good to hear that the efforts regarding this are not dead.
For reference, seems like you're referring to this PR: https://github.com/swaywm/wlroots/pull/258

**Comment by emersion** [comment]
Here's a comment about z-index issues: https://github.com/emersion/wlroots/pull/1#issuecomment-362821322

**Comment by emersion** [comment]
Reminder about things that needs to be done here:

* We need a configure event + make sure there's no FUC
* We need a positioner
* We need a way to fix z-index

And I'd like all of this to be as simple as possible to implement for compositors. I try to measure this complexity by comparing surface-layers with a "one protocol per use-case" approach.

**Comment by SirCmpwn** [comment]
I wonder if we could convince xdg-shell to pull their positioner into a separate protocol... probably not.

**Comment by Ongy** [comment]
xdg-shell went stable. So I doubt we'd have much success trying to get them to change the protocol at this point.
We could jsut rip it out into a standalone protocol and convince other that need it to use it as well though.
