### ISSUE TITLE
State that this project has migrated to freedesktop.org GitLab

### ISSUE THREAD

**Issue by TheEvilSkeleton** [swaywm/wlr-protocols#109]
I suggest stating that this project has been moved to freedesktop.org GitLab: https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/commit/93b0646e531fc7a01a943a411b7e540c8e0a35a6

I wouldn't mind submitting an MR.

**Comment by emersion** [comment]
We haven't migrated to gitlab.fdo, yet. These are just experiments. I've archived the GitLab project to make this clearer.
