### ISSUE TITLE
How to take a dependency on these xml files?

### ISSUE THREAD

**Issue by hossbeast** [swaywm/wlr-protocols#110]
Hello,

I am packaging an application for Arch Linux which uses wlr-data-control, and I am not sure how to properly consume the xml file.

I need to be able to do this when I build the application,

```
wayland-scanner private-code wlr-data-control.xml wlr-data-control.c
```

In arch linux, `wayland-scanner` is provided by the `wayland` package.

There is also the `wayland-protocols` package, and it vends a bunch of xml files, but `wlr-data-control.xml` is not one of them.

The README of this package tells me that pulling from `wlr-protocols` is not right, e.g. "New protocols should not be submitted to wlr-protocols. Instead, submit them to wayland-protocols."

Any advice? I really don't want to just copy the xml file into the project.

**Comment by kennylevinsen** [comment]
You are supposed to just copy the XML into the project report and set up wayland-scanner in your build system.

Random examples:
- https://github.com/swaywm/swaybg
- https://github.com/swaywm/swayidle (The KDE idle protocol, not a wlr protocol)
- https://git.sr.ht/~kennylevinsen/wlsunset
- https://git.sr.ht/~emersion/kanshi

**Comment by hossbeast** [comment]
interesting. Ok, will do that then.
