### ISSUE TITLE
Add protocol for enumerating shell surfaces and their locations

### ISSUE THREAD

**Issue by ddevault** [swaywm/wlr-protocols#14]
Locations respect to xdg-output, and the protocol should assume a surface could be rendered in several places.

**Comment by SirCmpwn** [comment]
Maybe we could add knobs to this for suggesting a view be minimized/maximized as well, suitable for making taskbars with then

**Comment by emersion** [comment]
Because of stuff like shadows and rounded corners, this kind of stuff won't be enough for e.g. screenshooting a single view (assuming you're talking about views rather than surfaces). Or at least not enough for clean screenshots of views without the background or other views.

Is there another use-case for knowing the position of shell views?

Is there any KDE prior art for this protocol?

**Comment by SirCmpwn** [comment]
>Because of stuff like shadows and rounded corners, this kind of stuff won't be enough for e.g. screenshooting a single view (assuming you're talking about views rather than surfaces). Or at least not enough for clean screenshots of views without the background or other views.

We would probably use that geo thing that xdg has to tell the compositor where the UI ends and the bullshit begins

>Is there another use-case for knowing the position of shell views?

slop

There was also an old BeOS hack which drew moeblobs sitting on your windows, we could relive that dream with this + layer surfaces

>Is there any KDE prior art for this protocol?

@davidedmundson

**Comment by Ongy** [comment]
How should the user select? Screenshot the entire screen and then select on that?
I think it would be better UX to have a view-selector interactivity, that allows a client to have the compositor provide the view selection (e.g. croshair cursor)

Prior art: wayland-wall contains a protocol intended for docks/task bars that provides utility to enumerate/render/switch to views.

**Comment by emersion** [comment]
Prior art: https://github.com/KDE/kwayland/blob/master/src/client/protocols/plasma-window-management.xml
