### ISSUE TITLE
Add a protocol to change output properties

### ISSUE THREAD

**Issue by agx** [swaywm/wlr-protocols#15]
It should be possible to change output resolution, scaling and rotation via a wayland protocol so that clients like gnome-control-center can do so without private protocol extensions. We could start simple with output transforms and scaling and refine the protocol in later revisions.

**Comment by emersion** [comment]
Prior art from KDE: https://github.com/KDE/kwayland/blob/master/src/client/protocols/output-management.xml

**Comment by agx** [comment]
That would need

**Comment by Ongy** [comment]
IMO we should avoid wl-output (and therefore) xdg-output for a management protocol.
The wl-output doesn't exist, when the output is off/unconfigured. And a management protocol should (at least IMO) support these states. 

Though I would appreciate if any way to identify the output to the user is required to be equivalent to the name/description used in xdg-output-v2.

**Comment by agx** [comment]
This could also contain red shifting / color temperature like in https://github.com/jonls/redshift/blob/master/src/gamma-drm.c#L272

**Comment by emersion** [comment]
>This could also contain red shifting / color temperature like in https://github.com/jonls/redshift/blob/master/src/gamma-drm.c#L272

This has been implemented in wlroots with https://github.com/giucam/orbital/blob/master/protocol/gamma-control.xml

**Comment by agx** [comment]
Hi,
On Wed, May 30, 2018 at 02:46:00PM +0000, emersion wrote:
>    This has been implemented in wlroots with
>    [2]https://github.com/giucam/orbital/blob/master/protocol/gamma-control.xml

Uhh...nice. Thanks.
 -- Guido

**Comment by emersion** [comment]
More prior art, though it doesn't seem high-quality: https://lists.freedesktop.org/archives/wayland-devel/2014-April/014092.html

**Comment by emersion** [comment]
GNOME uses this D-Bus protocol: https://gitlab.gnome.org/GNOME/mutter/blob/master/src/org.gnome.Mutter.DisplayConfig.xml
