### ISSUE TITLE
Request: Idle protocol

### ISSUE THREAD

**Issue by rektide** [swaywm/wlr-protocols#33]
Hello. In sway#3384 I opened a request for a way for applications to be able to detect if a user had gone idle. I got linked to KDE's [wayland idle protocol](https://github.com/KDE/kwayland/blob/master/src/client/protocols/idle.xml), which seems like it might be good to incorporate here.

**Comment by ascent12** [comment]
I don't think there is much value in creating our own protocol version for this. Any attempts to further standardise this should be done in upstream wayland-protocols.
I don't recall if anyone has tried to do that or has brought it up yet.

Knowing of a certain key player, I have a feeling that this is going to play out in an extremely annoying way.

**Comment by ddevault** [comment]
I'm not opposed to adopting that protocol, if KDE is interested. @davidedmundson

**Comment by ddevault** [comment]
Adopting in the sense of putting it in wlr-protocols and rehoming it under the wlr namespace, rather. wlr-protocols has been becoming a de-facto secondary home for Wayland protocol standardization given that wayland-protocols hasn't been accomodating of our upstreaming needs.

**Comment by emersion** [comment]
Submitted to wayland-protocols instead: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/29
