### ISSUE TITLE
Virtual pointer protocol

### ISSUE THREAD

**Issue by emersion** [swaywm/wlr-protocols#36]
We have a virtual keyboard protocol, but we're missing a virtual pointer one. Could be useful for remote control and remote desktop.

**Comment by emersion** [comment]
Protocol draft by @atx: https://github.com/atx/wlr-protocols/blob/master/unstable/wlr-virtual-pointer-unstable-v1.xml

**Comment by ddevault** [comment]
I'm not sure why virtual pointers would need anything beyond what, for example, the wayland backend provides.

**Comment by ddevault** [comment]
Hm, I'm not fond of that idea. The Wayland protocol does not already encode libinput, we would be making it less portable.

**Comment by swick** [comment]
It does not add a dependency on libinput but evdev (yes, the name is misleading in that way).

pq mentioned that this would not work for use cases where you want to move the pointer to a specific location since the events (probably) get modified in some form by the compositor. It seems like both solution have something that the other can't provide.

**Comment by ddevault** [comment]
Right, it can't just be the inverse of wl_pointer. I think we should aim for the inverse of wl_pointer plus an absolute motion event modelled after the libinput API.

**Comment by ddevault** [comment]
Perhaps plus a suggestion of which wl_output the pointer prefers to be on? This is something we can theoretically get out of udev for real input devices but I don't think we have the code.

**Comment by emersion** [comment]
>Perhaps plus a suggestion of which wl_output the pointer prefers to be on?

Maybe. The output would be useful for absolute events only.

Note that pointers are generally not mapped to outputs. Touch devices and tablets are.

> This is something we can theoretically get out of udev for real input devices but I don't think we have the code.

No, there's no way to get this from udev. Other compositors resort to heuristics (e.g. trying to map a touch device to the first integrated display), but that doesn't work in all cases.

**Comment by ddevault** [comment]
>Note that pointers are generally not mapped to outputs. Touch devices and tablets are.

This is only true of the traditional desktop paradigm, but for many use-cases (wayland backend, x11 backend, vnc) this is not true.

**Comment by emersion** [comment]
Implemented in https://github.com/swaywm/wlr-protocols/pull/58
