### ISSUE TITLE
Layer shell set_app_id?

### ISSUE THREAD

**Issue by wmww** [swaywm/wlr-protocols#40]
XDG shell has a `set_app_id` request:
```
Set an application identifier for the surface.

The app ID identifies the general class of applications to which
the surface belongs. The compositor can use this to group multiple
surfaces together, or to determine how to launch a new application.

For D-Bus activatable applications, the app ID is used as the D-Bus
service name.

The compositor shell will try to group application surfaces together
by their app ID. As a best practice, it is suggested to select app
ID's that match the basename of the application's .desktop file.
For example, "org.freedesktop.FooViewer" where the .desktop file is
"org.freedesktop.FooViewer.desktop".

See the desktop-entry specification [0] for more details on
application identifiers and how they relate to well-known D-Bus
names and .desktop files.

[0] http://standards.freedesktop.org/desktop-entry-spec/
```
Is there any reason Layer surfaces shouldn't also have this request? Could this replace the somewhat confusing `namespace` argument in the constructor?

**Comment by emersion** [comment]
`namespace` is different: it indicates the category. For instance Firefox would have an `app_id` set to `firefox` but a namespace set to `web-browser` (doesn't make a lot of sense in this context, but you get the idea).

`namespace` is used to resolve conflicts between e.g. a screenlocker and a virtual keyboard.

What would you use `app_id` for?

**Comment by wmww** [comment]
Ah. I thought the namespace was supposed to be unique to an application. I suppose MATE panel's namespace should be `"panel"` then, instead of `"mate-panel"`. I'm not sure exactly what `set_app_id` is used for. If it can't replace namespace, I suppose I should have a reason for it to exist before proposing it.

**Comment by emersion** [comment]
>I'm not sure exactly what set_app_id is used for.

`app_id` is used by e.g. window switchers (docks, bars and the like) to provide an icon (among other things). It directly maps to a `.desktop` file.
