### ISSUE TITLE
layer-shell: Notify of fullscreen/maximize

### ISSUE THREAD

**Issue by AdrianVovk** [swaywm/wlr-protocols#45]
Hello,

Currently, layer-shell has no signal to indicate that some surface has gone full-screen and will cover the panel. For simple panels, this is fine. I, however, am trying to build a DE with Wayfire, and it would be great to use layer-shell (if my users want to run my DE's components on Sway for tiling, for example). I have functionality where the super key will open the application menu, and the panel pops up temporarily over fullscreened surfaces. I also have a Super + T binding that pops up the panel for a few hundred ms to check the time or whatnot. layer-shell does not allow me in any way to know when a surface has gone fullscreen, so I cannot do any of this. If this is implemented separately from layer-shell, there needs to be some way for clients to tell the compositor that they handle fullscreen windows and shouldn't be forced below them.

It also seems fitting that layer-shell could notify the panel when a client is maximized. My panel is translucent when nothing is tiled/maximized, but should go fully opaque when something is. I'm certain this is a common usecase (Pantheon, GNOME, etc). This could go into a separate protocol if need be.

Thank you!

**Comment by emersion** [comment]
Window management is out-of-scope for layer-shell.

However another protocol already exposes maximized windows: https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml

@ammen99 Maybe fullscreen could be added too?

**Comment by ammen99** [comment]
@emersion The behavior that we want here is something else, i.e "If the current workspace has a fullscreen window, hide the panel". It depends on the "focused" workspace and on the view state.

**Comment by emersion** [comment]
Would foreign-toplevel-management + a workspace protocol be enough?

**Comment by ammen99** [comment]
Probably yes, with an additional fullscreen mode for foreign-toplevel (I'll send a patch for that soon)

**Comment by AdrianVovk** [comment]
How would I signal compositors to not place my panel under fullscreened surfaces?

**Comment by ammen99** [comment]
@AdrianVovk by placing it in the overlay layer?

**Comment by ammen99** [comment]
Actually I think we don't even need the workspace protocol for this. The panel can just check whether the currently activated toplevel is fullscreen, and if yes, then autohide.

However if the panel also needs to know if there is a maximized window on the current workspace, it will need a workspace protocol as well.

**Comment by emersion** [comment]
If you have two screens and a non-activated fullscreen toplevel on one of them, will that still work?

**Comment by ammen99** [comment]
> If you have two screens and a non-activated fullscreen toplevel on one of them, will that still work?

Sadly no. But then I am not sure how to fix this - a workspace protocol won't be enough, since the panel wants to know whether the topmost window on a given output is fullscreen.

**Comment by AdrianVovk** [comment]
Doesn't foreign-toplevel-management tell panels which output each view is on?

**Comment by ammen99** [comment]
Yes, but this isn't enough - if you have another view on top of the fullscreen output, you usually want to show the panel (GNOME and Wayfire do this).

**Comment by AdrianVovk** [comment]
Well, then the fullscreen view is no longer focused/active/whatever the proto calls it

For example (would be in the panel's code):
```
gboolean maximized = FALSE:
foreach (view) {
  if (view->output != panel->output) continue;
  if (view->is_focused)
     panel->set_fullscreen(view->is_fullscreen);
  if (view->is_maximized) maximized = TRUE:
}
panel->set_opaque(maximized);
```

**Comment by ammen99** [comment]
What happens if I switch to another workspace? Also, what happens if I have a fullscreen window, but press Alt-Tab (or whatever binding to switch the focused window)?

**Comment by AdrianVovk** [comment]
If you switch to another workspace, the fullscreen window should no longer be active and the panel will appear. Alt-Tab should behave the same way.

**Comment by ammen99** [comment]
@AdrianVovk Then we come to the problem which emersion described, if you have a fullscreen window on one output, and you focus the other output, the fullscreen window will lose the activated state.

**Comment by AdrianVovk** [comment]
Maybe have a new state? If a window is active it's state is `active`, if it is active but then the output gets deactivated it becomes `active_on_deactivated_output` or something like that

**Comment by AdrianVovk** [comment]
Now we just need a way to distinguish workspaces for fullscreen

**Comment by AdrianVovk** [comment]
Ah this should probably be closed. I just leave my panel under fullscreen windows and then when necessary I pop up onto a layer above fullscreen windows
