### ISSUE TITLE
Add a way to allow apps to be raised to top of the window stack

### ISSUE THREAD

**Issue by agx** [swaywm/wlr-protocols#63]
gtk apps have a way to request to be presented to the user (https://github.com/GNOME/gtk/blob/mainline/gdk/wayland/protocol/gtk-shell.xml#L46) which allows e.g. for 'one instance' applications if launched a second time to be brought to foreground on second launch. This e.g happens when an application is already running and a mail client spawns `gnumeric foo.odt`.

I looked around in xdg_* and did not see anything matching, should we add something like that to `wlr-*`, should that be a separate protocol? I'm happy to cook up something but don't want to duplicate things.

**Comment by emersion** [comment]
There's an RFC for this on the mailing list: https://patchwork.freedesktop.org/series/68075/

**Comment by agx** [comment]
@emersion thanks, i'll close this then if there's an upstream proposal already.

**Comment by agx** [comment]
really closing as suggested above.
