### ISSUE TITLE
Add DMA-BUF support to screencopy

### ISSUE THREAD

**Issue by emersion** [swaywm/wlr-protocols#73]
This would perform a GPU copy instead of a CPU one. screencopy already uses `wl_buffer` so it shouldn't be too hard.

- Indicate which device to allocate buffers on
- Indicate the modifier
- (Future  issue) How does that play with explicit sync?

**Comment by emersion** [comment]
Implementation detail: on the compositor side, either of these could be used:

* https://www.khronos.org/registry/OpenGL/extensions/ANGLE/ANGLE_framebuffer_blit.txt (https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3149)
* https://www.khronos.org/registry/OpenGL/extensions/NV/NV_framebuffer_blit.txt

**Comment by ammen99** [comment]
Out of curiosity, why would we want this instead of the export-dmabuf approach?

**Comment by ascent12** [comment]
I consider export-dmabuf to be borderline broken, and has some pretty bad race conditions. While copy-to-dmabuf isn't perfectly efficient, it'll still be pretty good, and I think it's much more preferable.

**Comment by emersion** [comment]
I disagree. Renderer v6 should allow us to mitigate race conditions in export-dmabuf.

**Comment by ascent12** [comment]
By throwing out any allocations once they've been exported?

**Comment by emersion** [comment]
No, by adding a "release" request and allowing the client to keep a reasonable number of DMA-BUFs locked.
