### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by tbm** [swaywm/wlr-protocols#79]
`unstable/wlr-output-management-unstable-v1.xml`

```
      <arg name="refresh" type="int" summary="vertical refresh rate in mHz"/>
...
      <arg name="refresh" type="int" summary="vertical refresh rate in mHz or zero"/>
```

s/mHz/MHz/ ?

`unstable/wlr-output-power-management-unstable-v1.xml`

```
      <entry name="invalid_mode" value="1" summary="inexistent power save mode"/>
```

s/inexistent/nonexistent/ ?

**Comment by hd1ex** [comment]
> s/mHz/MHz/ ?

Actually this means **milli-hertz**.
They did this to fit a fractional frequency into an integer value.
So there should be no typo here [(see the description in the core wayland protocol)](https://gitlab.freedesktop.org/wayland/wayland/-/blob/master/protocol/wayland.xml#L1183).

> s/inexistent/nonexistent/ ?

I'm no native English speaker but it seems like the word _inexistent_ is more a slangish word?

**Comment by emersion** [comment]
Feel free to send a PR to improve the second one. As @hd1ex said the first one is not a typo.
