### ISSUE TITLE
Make wlr-protocols into an installable package

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlr-protocols#8]
Similar to how wayland-protocols is an installable package, we should investigate whether or not it would be better to have this as an installable package as well.

This way people could bring it in as a dependency into their projects. The alternative is to have people copy it over which makes updates hard and subjects us to protocol drift.

Required:

* Gather feedback from wlr-protocols users to determine whether or not this is a good idea.
* Add a build system (meson or autotools) that simply installs the protocols probably in some directory in `/usr/share`.

**Comment by emersion** [comment]
Also add a pkg-config file with the `pkgdatadir` variable set.

**Comment by SirCmpwn** [comment]
We should probably do this
