### ISSUE TITLE
Formally reject new protocols

### ISSUE THREAD

**Issue by emersion** [swaywm/wlr-protocols#88]
New protocols should go in wayland-protocols' ext namespace, which has no more inclusion requirements than this repo, but also offers reviews by non-wlroots people and allows to host all protocols in the same place.

Proposal: reject new protocols in wlr-protocols. Only accept updates for protocols not yet included in wayland-protocols.

cc @ddevault

**Comment by agx** [comment]
This sounds good - maybe it would be good to mention how to do that in the `README.md` of this repo?

**Comment by ddevault** [comment]
ack
