### ISSUE TITLE
foreign-toplevel-management get previous opened toplevels

### ISSUE THREAD

**Issue by santouits** [swaywm/wlr-protocols#91]
Hi, as far I can tell there isn't an event for the compositor to give to the client all the previous opened toplevels info. I mean if I have a taskbar that I opened after I opened some windows, the taskbar doesn't have a way to know that they exist, right?

**Comment by emersion** [comment]
The compositor should broadcast all current toplevels when the client binds to foreign-toplevel-management.

**Comment by ammen99** [comment]
Yes, exactly what @emersion said. When the client first binds the wayland global, you will get events for the toplevels. That's why it is a good idea to add a listener immediately after binding the global, so that you don't miss any events. Is it not working?
