### ISSUE TITLE
layer-shell: Better focus policy for top and overlay layer surfaces

### ISSUE THREAD

**Issue by zzag** [swaywm/wlr-protocols#99]
The layer-shell protocol spec indicates that the compositor has to take the layer into account when it decides if a surface needs to become focused if the keyboard interactivity flag has been changed. While it makes total sense for surfaces in the background and the bottom layer, such a focus policy may break user's expectations with regards to what surfaces become focused if there is a persistent layer surface in the overlay layer.

For example, imagine that there is a notes widget that is in the overlay layer and the corresponding layer surface has the keyboard interactivity flag on. Now, if the user presses Meta to open a start menu (sorry for my Windows lingua), the start menu won't be focused because it might be in a layer that's below the overlay notes widget. According to the spec, it's an expected outcome, but from user's perspective, it's not.

**Comment by ammen99** [comment]
Isn't this basically the same problem as #32? You have a layer surface which can receive keyboard focus, but doesn't grab it?

**Comment by zzag** [comment]
Yep, it's related to #32. Closing this issue
